POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "mael",
    "password": "12345",
    "name": "el",
    "email": "syamaail@utem.edu.my"
}

###

GET http://localhost:3000/bye

###

GET http://localhost:3000
